### ISSUE TITLE
moz.final.3.emailpartner_1-en-US.webm and moz.final.3.emailpartner_1-en-US.mp4 files are 404s

### ISSUE THREAD

**Issue by stephendonner** [mozilla/advocacy.mozilla.org#217]
There are a couple missing static assets when loading https://advocacy.mozilla.org/en-US/encrypt/codemoji-b/1

https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.3.emailpartner_1-en-US.mp4

https://d24kjznqej0s8a.cloudfront.net/2016/encryption_campaign/moz.final.3.emailpartner_1-en-US.webm

**Comment by stephendonner** [comment]
Actually, it looks like they have a content-type of "html" and the correct asset loads after?

<img width="1792" alt="screen shot 2016-07-12 at 3 34 07 pm" src="https://cloud.githubusercontent.com/assets/387249/16785976/18eabd5a-4846-11e6-8e60-33cc4ee801cd.png">

**Comment by ScottDowne** [comment]
Kinda intended. We have some localized videos. So it first tries to find a localized version for whatever locale you're in, and if that fails, it uses the default.

In you're case it's trying to load en-US because that's the locale you're in, which isn't there because it's the same as the default.

To see this, go to https://advocacy.mozilla.org/de/encrypt/codemoji/2 and you'll see a case where we actually find a localized video.

We just added this so our content for this is low. We're seeing if we want to push for more localized content.

Happy to discuss issues and solutions though if this is bad practice and is causing issues, or just looked odd :)
