### ISSUE TITLE
Update theming of *PNI to remove holiday images and content

### ISSUE THREAD

**Issue by alanmoo** [mozilla/advocacy.mozilla.org#495]
Assets: https://drive.google.com/drive/folders/1zfwGqBfS6n3y-z6UTQSvSuQ3f5GWycNU?usp=sharing
RedPen: https://redpen.io/p/ajf2da463e476f3864

**Comment by alanmoo** [comment]
@beccaklam Where are the image assets for the latest updates? Do you have Sketch files too?

**Comment by gvn** [comment]
@beccaklam Which option should I build?

**Comment by beccaklam** [comment]
@alanmoo I do, but they're not that organized ... do you need the file organized in a certain way?

**Comment by beccaklam** [comment]
@gvn I would build this version first:
![landing page](https://user-images.githubusercontent.com/20977376/35159349-f25a0600-fd07-11e7-8d23-2e968653001a.jpg)
and here is the sketch file with all the applicable mock ups we talked about yesterday:
https://drive.google.com/open?id=1PpaeOhERQKBwFDCVqX-DSqWbxcojYjSu
CC: @alanmoo @HPaulJohnson

**Comment by natalieworth** [comment]
@gvn @alanmoo @beccaklam Added the last 'Smart TV' image in the google folder: https://drive.google.com/drive/u/1/folders/1zfwGqBfS6n3y-z6UTQSvSuQ3f5GWycNU

**Comment by gvn** [comment]
Do we have actual copy for the Smart TV section?

**Comment by natalieworth** [comment]
cc @caltrider do you know if we have copy yet? ^

**Comment by caltrider** [comment]
@natalieworth @gvn It's almost ready. Janice was going to have her reviews done on Friday. I pinged her today to see if she was done because I don't see them in the doc yet. Here's [the doc](https://docs.google.com/spreadsheets/d/1szZeBKAib8n3QOKZ6Th5ao3XrJr8CDdD9VDL6t6Tgyo/edit#gid=1540325979) where they will be: tab 1 "streaming tv devices" has the blurbs and product links and prices and links to product images, tab 2 "streaming tv janice" will have janice's reviews.  I'll ping everyone here when I hear from her.

**Comment by natalieworth** [comment]
Also just nothing from @caltrider that the title of the category should be “Streaming TV” rather than smart TV (we’re not actually reviewing any tvs, just the devices that let you stream things to them.

**Comment by gvn** [comment]
FYI: There's another ticket for Smart TV section: #496 so I'm going to leave it out of this PR...

**Comment by caltrider** [comment]
Can we change the word "gift" on the landing page subhead to "things" to help de-holidayify the page? @gvn @beccaklam @alanmoo
